First draft
Holo-Host/holo-hosting-app-proto pull request #1
Opened 2018-08-31 17:09 UTC by maackle

2018-09-04 19:17 UTC, neonphog requested changes
Nice! I love this as a starting point. Marking as "request changes" just for the bundle naming thing.

2018-09-04 19:17 UTC, neonphog commented on scripts/build.sh
> +&& rm src/dna/$ZOME/tsconfig.json
Even though it ends up being a lot more verbose to accomplish the same task, I tend toward writing nodejs scripts for things like this so they work in windows shell. (don't let this hold anything up, just a potential thought for the future)

2018-09-04 19:17 UTC, neonphog commented on src/dna/requests/requests.ts
> +  const {agentHash} = request;
This may not be the place for this, but I haven't been a big part of the code-style discussion. In javascript, I really like the "standard js" style. There is a typescript analyzer too: https://standardjs.com/#typescript

2018-09-04 19:17 UTC, neonphog commented on src/dna/serviceLogs/serviceLogs.ts
> +const demoBundle = makeHash('serviceLogBundle', startBundle);
I think we might want a different term to distinguish from the basic holochain concept of a "bundle".

(https://github.com/holochain/holochain-proto-types/blob/master/index.d.ts#L19)

2018-09-04 19:36 UTC, maackle commented on src/dna/serviceLogs/serviceLogs.ts
> +const demoBundle = makeHash('serviceLogBundle', startBundle);
Good point 👍

2018-09-05 00:56 UTC, maackle commented on src/dna/requests/requests.ts
> +  const {agentHash} = request;
👍 Added tslint as a build step

2018-09-05 00:59 UTC, maackle commented
@neonphog thanks for the feedback, I added `tslint --fix` as a build step and renamed "bundle" to "batch", though that whole notion might go away once I rework how log signing works.

2018-09-05 14:16 UTC, neonphog approved these changes
Awesome! Looks good to me :+1:

2018-09-05 16:05 UTC, merged